### ISSUE TITLE
No Gradient with Deepspeed #44

### ISSUE THREAD

**Issue by jzhang38** [a-r-r-o-w/cogvideox-factory#63]
### System Info / 系統信息

A100, new conda environment installed as instructed

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Hi, I tried to set the accelerate configs to deepspeed and then there is no gradient. (grad_norm = 0, no gradient, and model not updating).

It is fine under DDP(MULTI-GPU) and single GPU training.

To reproduce:

1. use train_text_to_video_sft.sh
2. change the config to accelerate_configs/deepspeed.yaml

### Expected behavior / 期待表现

Maybe look into this issue?

**Comment by a-r-r-o-w** [comment]
This is because the script tries to calculate gradnorm after DeepSpeed already performs the gradient update (the backward pass is handled internally in DeepSpeed so I'm not sure how we can get the gradients for reporting). I think it might require adding a backward hook to be able to grab the gradients before DeepSpeed clears them out - I'm not completely sure and haven't had the time to look at it. The training happens correctly (see [this](https://wandb.ai/aryanvs/cogvideox-lora/runs/565k2ach?nw=nwuseraryanvs) training run), and it's just that we report the gradnorm incorrectly

Any PRs fixing the computation are welcome :)

**Comment by jzhang38** [comment]
Thanks!
